<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="TestSuite2" duration-ms="544497" started-at="2015-06-14T19:27:13Z" finished-at="2015-06-14T19:36:17Z">
    <groups>
      <group name="Prod">
        <method signature="NewTest.testAddDevice()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testAddDevice" class="test.java.CloudTest.NewTest"/>
        <method signature="NewTest.testControl()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testControl" class="test.java.CloudTest.NewTest"/>
        <method signature="NewTest.testDeleteDevice()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testDeleteDevice" class="test.java.CloudTest.NewTest"/>
        <method signature="NewTest.testLogin()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testLogin" class="test.java.CloudTest.NewTest"/>
        <method signature="NewTest.testLogout()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testLogout" class="test.java.CloudTest.NewTest"/>
      </group> <!-- Prod -->
      <group name="Dev">
        <method signature="NewTest.testAddDevice()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testAddDevice" class="test.java.CloudTest.NewTest"/>
        <method signature="NewTest.testControl()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testControl" class="test.java.CloudTest.NewTest"/>
        <method signature="NewTest.testDeleteDevice()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testDeleteDevice" class="test.java.CloudTest.NewTest"/>
        <method signature="NewTest.testLogout()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testLogout" class="test.java.CloudTest.NewTest"/>
      </group> <!-- Dev -->
    </groups>
    <test name="ProdTest" duration-ms="544497" started-at="2015-06-14T19:27:13Z" finished-at="2015-06-14T19:36:17Z">
      <class name="test.java.CloudTest.NewTest">
        <test-method status="PASS" signature="BeforeTest()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="BeforeTest" is-config="true" duration-ms="298" started-at="2015-06-14T22:27:13Z" finished-at="2015-06-14T22:27:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeTest -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="setUp" is-config="true" duration-ms="26724" started-at="2015-06-14T22:27:13Z" finished-at="2015-06-14T22:27:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testLogin() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testLogin()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testLogin" duration-ms="11270" started-at="2015-06-14T22:27:40Z" finished-at="2015-06-14T22:27:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="tearDown" is-config="true" duration-ms="311" started-at="2015-06-14T22:27:51Z" finished-at="2015-06-14T22:27:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="takeScreenShotOnFailure(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="takeScreenShotOnFailure" is-config="true" duration-ms="0" started-at="2015-06-14T22:27:51Z" finished-at="2015-06-14T22:27:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogin status=SUCCESS method=NewTest.testLogin()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testLogin() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenShotOnFailure -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="setUp" is-config="true" duration-ms="13801" started-at="2015-06-14T22:27:51Z" finished-at="2015-06-14T22:28:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testDeleteDevice() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testDeleteDevice()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testDeleteDevice" duration-ms="8989" started-at="2015-06-14T22:28:05Z" finished-at="2015-06-14T22:28:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at test.java.CloudTest.NewTest.testDeleteDevice(NewTest.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteDevice -->
        <test-method status="PASS" signature="takeScreenShotOnFailure(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="takeScreenShotOnFailure" is-config="true" duration-ms="650" started-at="2015-06-14T22:28:14Z" finished-at="2015-06-14T22:28:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testDeleteDevice status=FAILURE method=NewTest.testDeleteDevice()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testDeleteDevice() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenShotOnFailure -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="tearDown" is-config="true" duration-ms="279" started-at="2015-06-14T22:28:15Z" finished-at="2015-06-14T22:28:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="setUp" is-config="true" duration-ms="13377" started-at="2015-06-14T22:28:15Z" finished-at="2015-06-14T22:28:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testAddDevice() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testAddDevice()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testAddDevice" duration-ms="104042" started-at="2015-06-14T22:28:28Z" finished-at="2015-06-14T22:30:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddDevice -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="tearDown" is-config="true" duration-ms="335" started-at="2015-06-14T22:30:12Z" finished-at="2015-06-14T22:30:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="takeScreenShotOnFailure(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="takeScreenShotOnFailure" is-config="true" duration-ms="0" started-at="2015-06-14T22:30:12Z" finished-at="2015-06-14T22:30:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testAddDevice status=SUCCESS method=NewTest.testAddDevice()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testAddDevice() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenShotOnFailure -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="setUp" is-config="true" duration-ms="25500" started-at="2015-06-14T22:30:13Z" finished-at="2015-06-14T22:30:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testLogout() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testLogout()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testLogout" duration-ms="9027" started-at="2015-06-14T22:30:38Z" finished-at="2015-06-14T22:30:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogout -->
        <test-method status="PASS" signature="takeScreenShotOnFailure(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="takeScreenShotOnFailure" is-config="true" duration-ms="1" started-at="2015-06-14T22:30:47Z" finished-at="2015-06-14T22:30:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogout status=SUCCESS method=NewTest.testLogout()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testLogout() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenShotOnFailure -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="tearDown" is-config="true" duration-ms="286" started-at="2015-06-14T22:30:47Z" finished-at="2015-06-14T22:30:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="setUp" is-config="true" duration-ms="12642" started-at="2015-06-14T22:30:48Z" finished-at="2015-06-14T22:31:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testControl() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testControl()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testControl" duration-ms="316122" started-at="2015-06-14T22:31:00Z" finished-at="2015-06-14T22:36:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at test.java.CloudTest.tests.Control.outputControl(Control.java:147)
	at test.java.CloudTest.tests.Control.execute(Control.java:64)
	at test.java.CloudTest.NewTest.testControl(NewTest.java:270)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testControl -->
        <test-method status="PASS" signature="takeScreenShotOnFailure(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="takeScreenShotOnFailure" is-config="true" duration-ms="482" started-at="2015-06-14T22:36:16Z" finished-at="2015-06-14T22:36:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testControl status=FAILURE method=NewTest.testControl()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testControl() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenShotOnFailure -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="tearDown" is-config="true" duration-ms="334" started-at="2015-06-14T22:36:17Z" finished-at="2015-06-14T22:36:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.java.CloudTest.NewTest -->
    </test> <!-- ProdTest -->
  </suite> <!-- TestSuite2 -->
</testng-results>
